//// 2021.04.13 20:12
//#include <string>
//#include <vector>
//#include <unordered_map>
//using namespace std;
//
//vector<int> solution(string msg) {
//	unordered_map<string, int> map;
//	for (int i = 0; i < 26; i++) map.insert({ {(char)(i + 'A')}, i + 1 });
//	int idx = 26;
//	vector<int> answer;
//
//	for (int i = 0; i < msg.length();) {
//		string s = { msg[i] };
//		if (i < msg.length()) {
//			char next = msg[++i];
//			auto it = map.begin();
//			while (i < msg.length() && (it = map.find(s + next)) != map.end()) {
//				s += next;
//				next = msg[++i];
//			}
//			map.insert({ s + next, ++idx });
//		}
//		answer.push_back(map[s]);
//	}
//	return answer;
//}
//
//void main() {
//	solution("THATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITIS");
//}